# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "7.1.3"

# Use mysql as the database for Active Record
gem "mysql2", "0.5.6"

gem "phonelib", "0.8.7"

# LDAP connection
gem "activeldap", "6.1.0", require: "active_ldap/railtie"
gem "net-ldap", "0.19.0"

gem "smbhash", "1.1.0"

# Authentication
gem "devise", "4.9.3"
gem "devise-two-factor", "5.0"

gem "rqrcode", "2.2.0"

# Keep track of app settings such as read-only
gem "rails-settings-cached", "2.9.4"

# SMS OTP
gem "twilio-ruby", "6.9.1"

# This is neccessary due to Ruby 3.1/Psych 4.x incompatibility which causes YAML alias issues [https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias]
gem "psych", "5.1.2"

gem "newrelic_rpm"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "6.4.2"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

gem "mail", "2.8.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "ory-hydra-client", "1.11.8"

gem "activerecord-session_store", "2.1.0"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# SCIM V2 endpoint framework
gem "scimitar", "2.7.1"

gem "rack-attack", "6.7.0"

gem "departure", "6.6.0"
gem "device_detector", "1.1.2"
gem "flipper"
gem "flipper-active_record"
gem "flipper-ui"
gem "health_check"
gem "jwt"
gem "lograge", "0.14.0"
gem "playbook_ui", "13.17.0"
gem "puma-metrics", "1.3.0"
gem "pwned"
gem "ransack"
gem "redis", "5.0.8"
gem "saml_idp"
gem "sentry-rails"
gem "sentry-ruby"
gem "sidekiq", "7.2.1"
gem "sidekiq-cron", "1.12.0"
gem "vite_rails"
gem "will_paginate", "4.0.0"
gem "will_paginate-bootstrap", "1.0.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "pry-byebug", "3.10.1"
  gem "pry-rails", "0.3.9"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  gem "license_finder", "7.1.0", require: false

  gem "rubocop-powerhome", require: false

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "factory_bot_rails", "6.4.3"
  gem "openid_connect", "2.3.0"
  gem "rack_session_access", "0.2.0"
  gem "rspec"
  gem "rspec-its"
  gem "rspec-rails"
  gem "selenium-webdriver"
  gem "shoulda"
  gem "shoulda-matchers"
  gem "vcr"
  gem "webdrivers"
  gem "webmock"
end
